projects:
  myapp:
    schemaPath: amplify/backend/api/myapp/build/schema.graphql
    includes:
      - myapp/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: myapp/graphql
extensions:
  amplify:
    version: 3
